### ISSUE TITLE
OpenGL renders textures black.

### ISSUE THREAD

**Issue by 42mix** [VertexEngine/VertexEngine#23]
When trying to render textures, opengl renders them as black.

**To Reproduce**
**1.** Compile the entire application (use the CMakeLists in the root directory)
**2.** Copy `SandBox/res` into the same directory as the SandBox executable.
**3.** Run SandBox

**Expected behavior**
OpenGL renders the texture properly.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/54434922/84587127-393f3000-ae3a-11ea-912a-758a281cba9b.png)

 **OS:** Ubuntu 20.04
**OpenGL:** 4.6

**Comment by NonNullDinu** [comment]
Fixed in https://github.com/VertexEngine/VertexEngine/commit/f31b0089fd320af710f293a3a0b3f272b081bda9.
Closing
